#!/usr/bin/env python
import os
from cement.core import backend, foundation, hook, handler
import argparse
from pmtools import PmController
from pmtools.controller.project import ProjectController
from pmtools.controller.archive import ArchiveController
from pmtools.controller.analysis import AnalysisController
from pmtools.controller.deliver import DeliveryController
##from pmtools.controller.compress import CompressController
##from pmtools.controller.statusdb import StatusdbController
##from pmtools.controller.clean import CleanController
##from pmtools.controller.ls import LsController

CONFIGFILE=os.path.join(os.getenv("HOME"), ".pm.conf")

## Tried to set this in controller subclass but doesn't work?!?
## FIXME: move to separate config.py module
defaults = backend.defaults('analysis', 'archive', 'config', 'project','log')
defaults['analysis']['root']  = None
defaults['archive']['root']  = None
defaults['project']['root']  = None
defaults['project']['repos']  = None
defaults['config']['ignore'] = ["slurm*", "tmp*"]
defaults['log']['level']  = "INFO"
defaults['log']['file']  = os.path.join(os.getenv("HOME"), "log", "pm.log")

app = foundation.CementApp('pm', base_controller=PmController, config_defaults = defaults, extensions = ['json'])

try:
    handler.register(ProjectController)
    handler.register(ArchiveController)
    handler.register(AnalysisController)
    handler.register(DeliveryController)
    # handler.register(CompressController)
    # handler.register(CleanController)
    # handler.register(LsController)
    app.setup()
    print app.log
    app.log.warn("testing logging", "help")
        
    try:
        app.config.parse_file(CONFIGFILE)
    except:
        app.log.warn("No config file %s; please create and set relevant config sections" % CONFIGFILE)
        sys.exit()
    app.run()

finally:
    app.close()
