#!/usr/bin/env python
import os
from cement.core import foundation, hook, handler
import argparse
from pmtools.lib.config import config_defaults
from pmtools import PmController, PmApp, PmOutputHandler
from pmtools.controller.project import ProjectController
from pmtools.controller.archive import ArchiveController
from pmtools.controller.analysis import AnalysisController
from pmtools.controller.deliver import DeliveryController

CONFIGFILE=os.path.join(os.getenv("HOME"), ".pm.conf")

app = PmApp('pm', base_controller=PmController, config_defaults = config_defaults, extensions = ['json'], output_handler=PmOutputHandler)

try:
    handler.register(ProjectController)
    handler.register(ArchiveController)
    handler.register(AnalysisController)
    handler.register(DeliveryController)
    app.setup()
        
    try:
        app.config.parse_file(CONFIGFILE)
    except:
        app.log.warn("No config file %s; please create and set relevant config sections" % CONFIGFILE)
        sys.exit()
    app.run()
    app.render(app._output_data)

finally:
    app.close()
